### ISSUE TITLE
Nova syntax schema does not recognise subsyntax element

### ISSUE THREAD

**Issue by kopischke** [robb-j/nova-xml#2]
Nova’s syntax definitions [allows for a `subsyntax` element](https://docs.nova.app/syntax-reference/scopes/#subsyntaxes) instead of a `subscopes` one in Start-End scopes. The XML extension does flag these as invalid, however.

<img width="1145" alt="Nova subsyntax invalidation" src="https://user-images.githubusercontent.com/80906/130588079-0bcdc55c-850d-4515-a998-69f388cf6c10.png">

----
_Running Nova 7.3 on macOS 11.5.2 with XML extension version 0.1.1_

**Comment by robb-j** [comment]
Hey, thanks for the report. I've [released 0.2.0](https://github.com/robb-j/nova-xml/blob/main/XML.novaextension/CHANGELOG.md#version-02) which should fix this. Feel free to reopen this issue if something isn't correct!

**Comment by kopischke** [comment]
Just updated and can confirm the `subsyntax` linting error is gone. Sweet, and thanks!
