### ISSUE TITLE
Update lemminx binary

### ISSUE THREAD

**Issue by fbricon** [robb-j/nova-xml#5]
https://github.com/robb-j/nova-xml/blob/4f6c57705f111457182398c1f7040ab75d35fd49/bin/get-server.sh#L7

You can get the binary from GitHub [releases](https://github.com/redhat-developer/vscode-xml/releases/tag/0.21.0) now, eg.: https://github.com/redhat-developer/vscode-xml/releases/download/0.21.0/lemminx-osx-x86_64.zip

**Comment by robb-j** [comment]
Thanks for the updated url, I've changed it now and updated the extension to the latest version
